name: Deploy com ArgoCD

on:
  workflow_dispatch:
    inputs:
      cliente:
        description: "Cliente para deploy (A, B, C, D)"
        required: true
        type: choice
        options:
          - A
          - B
          - C
          - D

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cliente: A
            env: cliente-a
          - cliente: B
            env: cliente-b
          - cliente: C
            env: cliente-c
          - cliente: D
            env: cliente-d

    environment: ${{ matrix.env }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar acesso ao cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

      - name: Deploy com ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username ${{ secrets.ARGOCD_USER }} \
            --password ${{ secrets.ARGOCD_PASS }} --insecure

          argocd app sync ${{ github.event.inputs.cliente }}-app
