name: Deploy Template

on:
  workflow_dispatch:
    inputs:
      cliente:
        description: "Cliente para deploy (A, B, C, D)"
        required: true
        type: choice
        options:
          - A
          - B
          - C
          - D

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cliente: A
            env: cliente-a
          - cliente: B
            env: cliente-b
          - cliente: C
            env: cliente-c
          - cliente: D
            env: cliente-d

    environment: ${{ matrix.env }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar acesso ao cluster
        run: |
          echo "Acessando o cluster ${{ github.event.inputs.cliente }}"

      - name: Build 
        run: |
          echo "Build projeto $GITHUB_REPOSITORY"

      - name: Deploy com ArgoCD
        run: |
          echo "Deploy no argo do projeto $GITHUB_REPOSITORY no clisnete ${{ github.event.inputs.cliente }}"
